import { useState } from 'react'
import { ArrowUp, Quote, BookOpen, MessageSquareText } from 'lucide-react'
import { post } from '../api'
import type { Citation } from '../types'
import CitationView from '../components/CitationView'
export default function Ask() {
  const [question,setQuestion]=useState(''); const [scope,setScope]=useState(['notes','guidelines','textbook'])
  const [answer,setAnswer]=useState(''); const [citations,setCitations]=useState<Citation[]>([])
  const [selected,setSelected]=useState<Citation|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  async function ask(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setAnswer('');setCitations([]);try{const result=await post<{answer:string;citations:Citation[]}>('/api/library/ask',{question,scope});setAnswer(result.answer);setCitations(result.citations)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="max-w-4xl mx-auto"><p className="eyebrow">ANSWERS WITH A PAPER TRAIL</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Ask your sources.</h1><p className="text-sm text-slate-500 mt-2 mb-7">Exact excerpts from your library. No answers from general model knowledge.</p><section className="panel p-6"><div className="flex flex-wrap gap-4 items-center mb-5"><span className="text-xs font-semibold text-slate-500">Search in</span>{[['notes','My notes'],['guidelines','Guidelines'],['textbook','Textbooks']].map(([id,label])=><label key={id} className="text-xs flex items-center gap-2 text-slate-600"><input type="checkbox" className="!w-auto accent-teal-800" checked={scope.includes(id)} onChange={e=>setScope(prev=>e.target.checked?[...prev,id]:prev.filter(s=>s!==id))}/>{label}</label>)}</div><form onSubmit={ask}><label htmlFor="question" className="sr-only">Ask a question from your local library</label><textarea id="question" rows={3} maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What should my chest pain presentation document?"/><div className="flex items-center justify-between mt-4 gap-3"><p className="text-[11px] text-slate-400 flex items-center gap-2"><BookOpen size={14}/>Only indexed sources are searched.</p><button className="btn-primary" disabled={busy || !question.trim() || !scope.length}>{busy?'Searching locally…':'Ask library'}<ArrowUp size={16}/></button></div></form></section>
    {error && <p role="alert" className="error mt-5">{error}</p>}
    {answer ? <section className="panel p-6 mt-6"><div className="flex items-center gap-3 mb-5"><span className="w-9 h-9 rounded-lg bg-teal-50 grid place-items-center text-teal-800"><Quote size={18}/></span><div><h2 className="text-sm font-semibold">{citations.length ? 'From your library' : 'No supported answer'}</h2><p className="text-[10px] text-slate-400">{citations.length?'Verified verbatim excerpts · review the source':'The assistant will not fill gaps from memory.'}</p></div></div><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{answer}</p>{!!citations.length && <div className="border-t border-slate-100 mt-6 pt-5"><p className="eyebrow mb-3">SUPPORTING SOURCES</p><div className="flex flex-wrap gap-2">{citations.map((citation,i)=><button key={i} className="btn !text-xs !py-2 text-teal-800" onClick={()=>setSelected(citation)}><span className="rounded bg-teal-50 px-1.5 py-0.5">{i+1}</span>{citation.filename}, {citation.location_type==='section'?'section':'p.'} {citation.page}</button>)}</div><p className="text-[11px] text-slate-400 mt-3">Click a citation to inspect the exact passage in context.</p></div>}</section> : !busy && <div className="text-center py-16"><MessageSquareText size={33} className="mx-auto mb-5 text-slate-300"/><h2 className="text-base font-medium text-slate-600">Begin with something you're learning.</h2><p className="text-xs text-slate-400 mt-2">No sources yet? Load the sample library from My library.</p><div className="flex flex-wrap justify-center gap-2 mt-6">{['What does SOAP stand for?','What chest pain details should I document?','What fever details should I document?'].map(sample=><button key={sample} className="btn !text-xs" onClick={()=>setQuestion(sample)}>{sample}</button>)}</div></div>}
    {selected && <CitationView citation={selected} onClose={()=>setSelected(null)}/>}
  </div>
}
